name: Frontend CI

on:
  push:
    paths:
      - "TrendSpot/frontend/**"
      - ".github/workflows/frontend-ci.yml"
  pull_request:
    paths:
      - "TrendSpot/frontend/**"
      - ".github/workflows/frontend-ci.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: TrendSpot/frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      # (Optional) 테스트가 있다면 아래 주석 해제
      # - name: Run tests
      #   run: npm test
